https://secoli-com-br.preview-domain.com/wp-json/secoli/v1/agendar-contato?nome=max&email=maxsouza150@hotmail.com&telefone=829999-9999&nome_empresa=empresa%20teste&cnpj=1234234112341234&descricao=descricao%20teste